name: Build Only (Server + App)

on:
  workflow_dispatch:

env:
  VERSION: ${{ github.ref_type == 'tag' && github.ref_name || 'dev-build' }}

jobs:
  build-server:
    name: Build Server (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ext: ""
            simple_os: linux
          - os: windows-latest
            ext: ".exe"
            simple_os: windows
          - os: macos-latest
            ext: ""
            simple_os: macos

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: server/.python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Build server executable
        working-directory: server
        shell: bash
        run: |
            uv sync
            uv pip install pyinstaller
            uv run pyinstaller --onefile --name openmail-server --paths=. src/main.py

      - name: Rename executable to include version and OS
        run: |
          mkdir -p dist
          mv server/dist/openmail-server${{ matrix.ext }} dist/Openmail-Server_${{ env.VERSION }}_${{ matrix.simple_os }}${{ matrix.ext }}

  build-app:
    name: Build App (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    permissions:
        contents: write
    strategy:
        fail-fast: false
        matrix:
          include:
            - platform: 'macos-latest' # for Arm based macs (M1 and above).
              args: '--target aarch64-apple-darwin'
            - platform: 'macos-latest' # for Intel based macs.
              args: '--target x86_64-apple-darwin'
            - platform: 'ubuntu-22.04'
              args: ''
            - platform: 'windows-latest'
              args: ''

    steps:
      - uses: actions/checkout@v5

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: app/.bun-version

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (Linux)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
            sudo apt-get update
            sudo apt-get install -y \
              libwebkit2gtk-4.1-0 \
              libwebkit2gtk-4.1-dev \
              libjavascriptcoregtk-4.1-0 \
              libjavascriptcoregtk-4.1-dev \
              gir1.2-javascriptcoregtk-4.1 \
              gir1.2-webkit2-4.1 \
              libappindicator3-dev \
              librsvg2-dev \
              patchelf

      - name: Install frontend dependencies
        working-directory: app
        run: bun install

      - name: Build tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: app
          args: ${{ matrix.args }}

      - name: Rename app executable (macOS)
        if: startsWith(matrix.platform, 'macos')
        shell: bash
        run: |
            mkdir -p dist
            if [[ "${{ matrix.args }}" == *"aarch64-apple-darwin"* ]]; then
                ARCH_NAME="macos-arm64"
            elif [[ "${{ matrix.args }}" == *"x86_64-apple-darwin"* ]]; then
                ARCH_NAME="macos-x64"
            else
                ARCH_NAME="macos"
            fi
            echo "ARCH_NAME=$ARCH_NAME" >> $GITHUB_ENV

            mv app/src-tauri/target/*-apple-darwin/release/bundle/dmg/*.dmg \
            dist/Openmail_${{ env.VERSION }}_${ARCH_NAME}.dmg

      - name: Rename app executable (Linux)
        if: startsWith(matrix.platform, 'ubuntu')
        shell: bash
        run: |
            mkdir -p dist
            echo "ARCH_NAME=linux" >> $GITHUB_ENV
            mv app/src-tauri/target/release/bundle/appimage/*.AppImage \
            dist/Openmail_${{ env.VERSION }}_linux.AppImage
            mv app/src-tauri/target/release/bundle/deb/*.deb \
            dist/Openmail_${{ env.VERSION }}_linux.deb
            mv app/src-tauri/target/release/bundle/rpm/*.rpm \
            dist/Openmail_${{ env.VERSION }}_linux.rpm

      - name: Rename app executable (Windows)
        if: startsWith(matrix.platform, 'windows')
        shell: pwsh
        run: |
            New-Item -ItemType Directory -Force -Path dist | Out-Null
            echo "ARCH_NAME=windows" >> $env:GITHUB_ENV
            Move-Item "app/src-tauri/target/release/bundle/nsis/*.exe" `
            "dist/Openmail_${{ env.VERSION }}_windows.exe"
